### ISSUE TITLE
Can we expect version for Ububntu?

### ISSUE THREAD

**Issue by adarrra** [cs150bf/ever-notedown#17]
Hi,  are you have it in the plans for the near future?

**Comment by cs150bf** [comment]
Unfortunately the short answer is "no, I don't think so".

I guess I would like to elaborate just a little bit. Besides "I don't have time" and "I don't do any note-taking on Ubuntu myself", the main reason is that Evernote doesn't have an official client for Linux yet, as far as I know.   The main idea behind EVND is to take advantage of the Evernote client's scriptability (AppleScript for OSX, `ENScript.exe` for Windows)[1] so we can effectively use Atom as an alternate editor for it. Without an official Linux client, the whole thing is just a bit pointless.
That being said, there are 3rd-class Evernote clients for Linux, etc. But I think it will be quite complicated to put all the pieces together, assuming we're sticking to the "local scripting" thing.

But perhaps I should have asked which part of EVND are you interested in? If it's just the enhanced markdown rendering part, then it should work just fine on Linux; and there are also packages like [markdown-preview-plus](https://atom.io/packages/markdown-preview-plus) that are very well written and maintained. But if you're interested in the Evernote integration... well, it could still be implemented relatively easily with a little change of direction if someone is inclined to do so: instead of local scripting, go for the web API, authorization, and so on -- like how it's done in [sublime-evernote](https://github.com/bordaigorl/sublime-evernote) and in other similar projects. But I'm not sure if I could see a point in doing that myself. 

Thanks for you interest!

[1]: See "Local Scripting -> OSX/Windows" on the Evernote developers site:
- https://dev.evernote.com/doc/articles/applescript.php
- https://dev.evernote.com/doc/articles/enscript.php

**Comment by adarrra** [comment]
Thank you very much for so detailed answer, very interesting and useful for further thoughts
