### ISSUE TITLE
cannot import from evernote

### ISSUE THREAD

**Issue by adasfan** [cs150bf/ever-notedown#73]
i am able to search and find the evernote document from Atom but when i click to import it i see the Evernote app bouncing in the dock and nothing happens..

**Comment by adasfan** [comment]
i was using the version from the app store

**Comment by wallacexia** [comment]
Why close this issue? How to resovle it?
I open the develop console, it display this :
`Error: Command failed: /bin/sh -c osascript /var/folders/d4/4tth1dhs2576x_61cdbmrl9h0000gn/T/evernote-retrive-note-temp116620-41054-1kc5cm5.AppleScript
/var/folders/d4/4tth1dhs2576x_61cdbmrl9h0000gn/T/evernote-retrive-note-temp116620-41054-1kc5cm5.AppleScript:199:303: execution error: Evernote got an error: The operation couldn’t be completed. Operation not permitted (1)`

**Comment by cs150bf** [comment]
Hi Wallace,

I did not close this issue. The person who opened it closed it, I suppose
because they were able to solve the problem. There have been problems using
AppleScript with the Mac Apple Store version of Evernote client, you can
read more about this from the "Requirements" section from the EVND help
document
<https://www.evernote.com/shard/s68/sh/782d6000-361f-4963-b3c1-84ff6af2b625/971f599e4c39cd8f>.
The relevant part is:

"For EVND (particularly the *import* function) to work properly, you will
need the EN client installed with the dmg downloaded directly from the
offical website
<https://www.evernote.com/OutboundRedirect.action?dest=https%3A%2F%2Fevernote.com%2Fdownload%2F>,
*not* the one from the mac app store.(*Caveat* - Apparently the applescript
support is glitchy with the app store version of EN client. Something has
to do with “the way the app is sandboxed”
<https://www.evernote.com/OutboundRedirect.action?dest=https%3A%2F%2Fgithub.com%2Fjamietr1%2Fevernote-backup%2Fblob%2Fmaster%2FREADME.md>.
See more discussion here
<https://www.evernote.com/OutboundRedirect.action?dest=https%3A%2F%2Fgithub.com%2Fcs150bf%2Fever-notedown%2Fissues%2F5%23issuecomment-118221171>
.)"

Cheers,
HC

**Comment by cs150bf** [comment]
If you are having similar import problems and are reading this issue, please check whether you are using the Evernote client from the Mac App Store. You probably need to uninstall it to download the dmg from the offical Evernote site and install again.

The reason is that there have been problems using
AppleScript with the Mac Apple Store version of Evernote client, you can
read more about this from the "Requirements" section from [the EVND help
document](https://www.evernote.com/shard/s68/sh/782d6000-361f-4963-b3c1-84ff6af2b625/971f599e4c39cd8f).

The relevant part is:

> For EVND (particularly the _import_ function) to work properly, you will
> need the EN client installed with the dmg downloaded directly from [the
> offical website](https://www.evernote.com/OutboundRedirect.action?dest=https%3A%2F%2Fevernote.com%2Fdownload%2F), _not_ the one from the mac app store.(_Caveat_ - Apparently the applescript
> support is glitchy with the app store version of EN client. Something has
> to do with [“the way the app is sandboxed”](https://www.evernote.com/OutboundRedirect.action?dest=https%3A%2F%2Fgithub.com%2Fjamietr1%2Fevernote-backup%2Fblob%2Fmaster%2FREADME.md). See more discussion [here](https://www.evernote.com/OutboundRedirect.action?dest=https%3A%2F%2Fgithub.com%2Fcs150bf%2Fever-notedown%2Fissues%2F5%23issuecomment-118221171).)"

Cheers,
HC
